project:
  type: book
  output-dir: docs

# Quarto options for books
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Demo V2 Layouts"
  author: "ASKCR"
  date: today
  # this section determines which files will be added to the book as chapters
  chapters:
    - index.qmd
    - section-masonry.ipynb
    - section-grid.ipynb
    - section-fullimg.ipynb
  repo-url: https://github.com/calnfynn/section-demo-layouts
  repo-actions: [issue]
  # downloads: [pdf,docx,epub]
  cover-image: images/fmd10005860a.jpg
  navbar:
    background: primary
    search: true
    left:
      - text: "Masonry"
        href: section-masonry.html
      - text: "Grid"
        href: section-grid.html
      - text: "Full Screen Image"
        href: section-fullimg.html
  sidebar: false

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: false


format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    number-sections: false
    # Quarto allows a number of pre-packaged themes for the HTML version
    # You can choose between them using the documentation at 
    # https://quarto.org/docs/output-formats/html-themes.html
    theme: lux
    css: griddesign.css
    grid:
      sidebar-width: 0px
      margin-width: 0px
      body-width: 2000px
  # options for PDF output 
  # https://quarto.org/docs/reference/formats/pdf.html
  #pdf:
  #  documentclass: book
  #docx: 
  #  toc: true
  #epub: 
  #  toc: true    
