project:
  type: book
  output-dir: docs

# Quarto options for books
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Die barocken Ahnenporträts"
  author: "Simon Worthington"
  date: today
  # this section determines which files will be added to the book as chapters
  chapters:
    - index.qmd
    - section.ipynb
    - section-bs.ipynb
  #repo-url: https://github.com/TIBHannover/section-demo
  #repo-actions: [issue]
  #downloads: [pdf,docx,epub]
  cover-image: images/fmd10005860a.jpg
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - section.ipynb
      - section-bs.ipynb
  sidebar: false

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: true


format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    number-sections: false
    # Quarto allows a number of pre-packaged themes for the HTML version
    # You can choose between them using the documentation at 
    # https://quarto.org/docs/output-formats/html-themes.html
    theme: lux
    css: griddesign.css
    grid:
      sidebar-width: 0px
      margin-width: 0px
      body-width: 2000px
  # options for PDF output 
  # https://quarto.org/docs/reference/formats/pdf.html
  #pdf:
  #  documentclass: book
  #docx: 
  #  toc: true
  #epub: 
  #  toc: true    
